/**
 * The fibonacci sequence is a series of numbers that are generated by
 * adding the two previous numbers together.
 *
 * 1, 1 are the first two numbers. Combined, they make 2.
 * Then, 2 + 1 is 3.
 * At this point, the sequence is "1, 1, 2, 3"
 *
 * The sequence can go on forever, so ideally a function should have an exit condition
 * when it reaches a maximum number
 *
 * {@link https://en.wikipedia.org/wiki/Fibonacci_number}
 */
// Copilot was given "function fibonacci(n, max". It generated valid code without "(n, max", but had no exit condition
function fibonacci(n, max) {
  var a = 0, b = 1, c = 0;
  while (c < max) {
    console.log(a);
    a = b;
    b = a + b;
    c++;
  }
}

fibonacci(5, 10);
